/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FakerCoffee;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FakerCoffeeTest {

    

    @Test
    void CPFLenght() {
        assertEquals(14, FakerCoffee.gerarCPF().length());
    }

}
